## ##############################################################################
## Project: FPGA-Based Autonomous Elevator Control System
## Board: Digilent Basys 3 (Artix-7)
## Description: Physical Pin Mapping and Timing Constraints
## ##############################################################################

# ------------------------------------------------------------------------------
# System Clock Signal
# ------------------------------------------------------------------------------
# Defining the 100MHz board clock on pin W5. 
# A 10.00ns period constraint is created to ensure timing closure for the FSM and PWM logic.
set_property PACKAGE_PIN W5 [get_ports CLK100MHZ]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK100MHZ]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK100MHZ]

# ------------------------------------------------------------------------------
# User Inputs: Floor Request Buttons (Active Low)
# ------------------------------------------------------------------------------
# Buttons are connected to Pmod Header JB. 
# Internal PULLUP resistors are enabled to ensure a stable High state (3.3V) 
# when the button is not pressed. Pressing the button pulls the signal to Ground (0V).

## button[0] - JB2
set_property PACKAGE_PIN A16 [get_ports {button[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
	set_property PULLUP true [get_ports {button[0]}]
	
## button[1] - JB3
set_property PACKAGE_PIN B15 [get_ports {button[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
	set_property PULLUP true [get_ports {button[1]}] 
	
## button[2] - JB4
set_property PACKAGE_PIN B16 [get_ports {button[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
	set_property PULLUP true [get_ports {button[2]}] 

# ------------------------------------------------------------------------------
# Actuator: Servo Motor Output (PWM)
# ------------------------------------------------------------------------------
# Servo control signal on Pmod JB10. 
# This port outputs the 50Hz PWM signal generated by the servomotor_operation module.
set_property PACKAGE_PIN C16 [get_ports {servo}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {servo}]	

# ------------------------------------------------------------------------------
# Sensors: Magnetic Reed Switches (Active Low)
# ------------------------------------------------------------------------------
# Reed switches sense the physical location of the elevator. 
# Internal PULLUPs are used to handle the Active-Low sensor configuration.

## Reed Switch Floor 0 - JC4
set_property PACKAGE_PIN P18 [get_ports {reed_switch[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reed_switch[0]}]
	set_property PULLUP true [get_ports {reed_switch[0]}]
	
## Reed Switch Floor 1 - JC10
set_property PACKAGE_PIN R18 [get_ports {reed_switch[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reed_switch[1]}]
	set_property PULLUP true [get_ports {reed_switch[1]}]
	
## Reed Switch Floor 2 - JA4
set_property PACKAGE_PIN G2 [get_ports {reed_switch[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reed_switch[2]}]
	set_property PULLUP true [get_ports {reed_switch[2]}] 

# ------------------------------------------------------------------------------
# Visual Feedback: LEDs
# ------------------------------------------------------------------------------
# LEDs indicate registered floor requests.
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]

# ------------------------------------------------------------------------------
# 7-Segment Display
# ------------------------------------------------------------------------------
# Displays the current floor (0, 1, or 2).

# Segment Mapping (a-g)
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

# Anode Control (Digit Selectors)
set_property PACKAGE_PIN U2 [get_ports {an[0]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]	
    set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
